// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/harmony-retro/AtomicBloom.tsx": () => import("../components/mockups/harmony-retro/AtomicBloom.tsx"),
  "./components/mockups/harmony-retro/GoogieFutura.tsx": () => import("../components/mockups/harmony-retro/GoogieFutura.tsx"),
  "./components/mockups/harmony-retro/GroovyLounge.tsx": () => import("../components/mockups/harmony-retro/GroovyLounge.tsx")
};
